import type { FeedRun } from '@/types/app';

const IMG = {
  run1: 'https://images.unsplash.com/photo-1476480862126-209bfaa8edc8?w=800',
  run2: 'https://images.unsplash.com/photo-1571008887538-b36bbda08f4b?w=800',
  run3: 'https://images.unsplash.com/photo-1552674605-db6ffd4facb5?w=800',
  run4: 'https://images.unsplash.com/photo-1502904550040-7534597429ae?w=800',
  run5: 'https://images.unsplash.com/photo-1517963879433-6ad2b056d712?w=800',
  run6: 'https://images.unsplash.com/photo-1550345332-09e3ac987658?w=800',
  run7: 'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?w=800',
  run8: 'https://images.unsplash.com/photo-1546483875-ad9014c88eba?w=800',
  run9: 'https://images.unsplash.com/photo-1599058918144-1ffabb6ab9a0?w=800',
  run10: 'https://images.unsplash.com/photo-1486218119243-13883505764c?w=800',
  avatar1: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200',
  avatar2: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200',
  avatar3: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=200',
  avatar4: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200',
  avatar5: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200',
  avatar6: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=200',
  avatar7: 'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=200',
  avatar8: 'https://images.unsplash.com/photo-1545996124-0501ebae84d0?w=200',
  avatar9: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=200',
  avatar10: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=200',
};

const nowIso = new Date().toISOString();
const futureIso = (hoursFromNow: number) => new Date(Date.now() + hoursFromNow * 3600000).toISOString();

export const MOCK_FEED_RUNS: FeedRun[] = [
  {
    id: 'mock-run-1',
    creator_id: 'mock-user-1',
    title: 'Prospect Park Loop',
    location: 'Park Slope, Brooklyn',
    datetime: futureIso(24),
    distance: 10.5,
    pace: '5:30',
    image: IMG.run1,
    vibe_tags: ['Tempo', 'Long Run', 'Early Bird'],
    note: null,
    status: 'open',
    closed_at: null,
    created_at: nowIso,
    updated_at: nowIso,
    creator: {
      id: 'mock-user-1',
      name: 'Maya',
      age: 29,
      city: 'Brooklyn',
      photos: [IMG.avatar1],
      vibe_tags: ['Tempo', 'Long Run', 'Early Bird'],
    },
    requestStatus: null,
    requestId: null,
    distanceKm: 1.9,
  },
  {
    id: 'mock-run-2',
    creator_id: 'mock-user-2',
    title: 'Hampstead Heath Trail',
    location: 'Parliament Hill',
    datetime: futureIso(36),
    distance: 8,
    pace: '5:45',
    image: IMG.run2,
    vibe_tags: ['Long Run', 'Chill Pace', 'Beginner Friendly', 'berc Crew'],
    note: null,
    status: 'open',
    closed_at: null,
    created_at: nowIso,
    updated_at: nowIso,
    creator: {
      id: 'mock-user-2',
      name: 'James Cole',
      age: 31,
      city: 'London',
      photos: [IMG.avatar2],
      vibe_tags: ['Long Run', 'berc Crew'],
    },
    requestStatus: null,
    requestId: null,
    distanceKm: 3.4,
  },
  {
    id: 'mock-run-3',
    creator_id: 'mock-user-3',
    title: 'Regent Park Tempo Session',
    location: 'Regent Park Outer Circle',
    datetime: futureIso(42),
    distance: 7.2,
    pace: '4:58',
    image: IMG.run3,
    vibe_tags: ['Social', 'Evening', 'Coffee Run', 'berc Crew'],
    note: null,
    status: 'open',
    closed_at: null,
    created_at: nowIso,
    updated_at: nowIso,
    creator: {
      id: 'mock-user-3',
      name: 'Lena Brooks',
      age: 26,
      city: 'London',
      photos: [IMG.avatar3],
      vibe_tags: ['Evening', 'berc Crew'],
    },
    requestStatus: null,
    requestId: null,
    distanceKm: 2.1,
  },
  {
    id: 'mock-run-4',
    creator_id: 'mock-user-4',
    title: 'Canary Wharf Sunrise Miles',
    location: 'Canary Wharf Riverside',
    datetime: futureIso(18),
    distance: 9.5,
    pace: '5:08',
    image: IMG.run4,
    vibe_tags: ['Morning Run', 'Social', 'berc Crew'],
    note: null,
    status: 'open',
    closed_at: null,
    created_at: nowIso,
    updated_at: nowIso,
    creator: {
      id: 'mock-user-4',
      name: 'Ethan Ward',
      age: 30,
      city: 'London',
      photos: [IMG.avatar4],
      vibe_tags: ['Morning Run', 'berc Crew'],
    },
    requestStatus: null,
    requestId: null,
    distanceKm: 4.8,
  },
  {
    id: 'mock-run-5',
    creator_id: 'mock-user-5',
    title: 'Chelsea Bridge Easy Social',
    location: 'Chelsea Embankment',
    datetime: futureIso(30),
    distance: 6.4,
    pace: '5:52',
    image: IMG.run5,
    vibe_tags: ['Beginner Friendly', 'Social', 'Coffee Run', 'berc Crew'],
    note: null,
    status: 'open',
    closed_at: null,
    created_at: nowIso,
    updated_at: nowIso,
    creator: {
      id: 'mock-user-5',
      name: 'Maya Collins',
      age: 27,
      city: 'London',
      photos: [IMG.avatar5],
      vibe_tags: ['Beginner Friendly', 'berc Crew'],
    },
    requestStatus: null,
    requestId: null,
    distanceKm: 0.9,
  },
  {
    id: 'mock-run-6',
    creator_id: 'mock-user-6',
    title: 'Battersea Power Strides',
    location: 'Battersea Park Loop',
    datetime: futureIso(52),
    distance: 11.3,
    pace: '4:50',
    image: IMG.run6,
    vibe_tags: ['Long Run', 'Social', 'berc Crew'],
    note: null,
    status: 'open',
    closed_at: null,
    created_at: nowIso,
    updated_at: nowIso,
    creator: {
      id: 'mock-user-6',
      name: 'Noah Carter',
      age: 29,
      city: 'London',
      photos: [IMG.avatar6],
      vibe_tags: ['Long Run', 'berc Crew'],
    },
    requestStatus: null,
    requestId: null,
    distanceKm: 5.6,
  },
  {
    id: 'mock-run-7',
    creator_id: 'mock-user-7',
    title: 'Shoreditch Night Run',
    location: 'Shoreditch High Street',
    datetime: futureIso(60),
    distance: 8.1,
    pace: '5:20',
    image: IMG.run7,
    vibe_tags: ['Evening', 'Social', 'berc Crew'],
    note: null,
    status: 'open',
    closed_at: null,
    created_at: nowIso,
    updated_at: nowIso,
    creator: {
      id: 'mock-user-7',
      name: 'Ava Bennett',
      age: 25,
      city: 'London',
      photos: [IMG.avatar7],
      vibe_tags: ['Evening', 'berc Crew'],
    },
    requestStatus: null,
    requestId: null,
    distanceKm: 3.2,
  },
  {
    id: 'mock-run-8',
    creator_id: 'mock-user-8',
    title: 'Hyde Park Recovery Run',
    location: 'Hyde Park Serpentine',
    datetime: futureIso(26),
    distance: 5.8,
    pace: '6:02',
    image: IMG.run8,
    vibe_tags: ['Chill Pace', 'Beginner Friendly', 'Coffee Run', 'berc Crew'],
    note: null,
    status: 'open',
    closed_at: null,
    created_at: nowIso,
    updated_at: nowIso,
    creator: {
      id: 'mock-user-8',
      name: 'Lucas Reed',
      age: 32,
      city: 'London',
      photos: [IMG.avatar8],
      vibe_tags: ['Chill Pace', 'berc Crew'],
    },
    requestStatus: null,
    requestId: null,
    distanceKm: 1.7,
  },
  {
    id: 'mock-run-9',
    creator_id: 'mock-user-9',
    title: 'Richmond Riverside Progression',
    location: 'Richmond Bridge',
    datetime: futureIso(72),
    distance: 13.4,
    pace: '5:05',
    image: IMG.run9,
    vibe_tags: ['Long Run', 'Morning Run', 'berc Crew'],
    note: null,
    status: 'open',
    closed_at: null,
    created_at: nowIso,
    updated_at: nowIso,
    creator: {
      id: 'mock-user-9',
      name: 'Daniel',
      age: 34,
      city: 'Richmond, London',
      photos: [IMG.avatar9],
      vibe_tags: ['Long Run', 'Social'],
    },
    requestStatus: null,
    requestId: null,
    distanceKm: 6.3,
  },
  {
    id: 'mock-run-10',
    creator_id: 'mock-user-10',
    title: 'Greenwich Sprint & Coffee',
    location: 'Greenwich Park Observatory',
    datetime: futureIso(34),
    distance: 6.9,
    pace: '4:42',
    image: IMG.run10,
    vibe_tags: ['Social', 'Coffee Run', 'Morning Run', 'berc Crew'],
    note: null,
    status: 'open',
    closed_at: null,
    created_at: nowIso,
    updated_at: nowIso,
    creator: {
      id: 'mock-user-10',
      name: 'Ryan Blake',
      age: 27,
      city: 'London',
      photos: [IMG.avatar10],
      vibe_tags: ['Social', 'berc Crew'],
    },
    requestStatus: null,
    requestId: null,
    distanceKm: 2.9,
  },
];

export const MOCK_UPCOMING_RUNS = [
  {
    id: 'mock-up-1',
    title: 'Hampstead Heath Loop',
    datetime: '2023-10-14T08:00:00',
    distance: 12,
    attendees: 32,
    image: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=200',
  },
  {
    id: 'mock-up-2',
    title: 'Thames Night Sprint',
    datetime: '2023-10-17T18:30:00',
    distance: 5.5,
    attendees: 14,
    image: 'https://images.unsplash.com/photo-1514565131-fce0801e5785?w=200',
  },
];

export const MOCK_PROFILE_PHOTOS = [
  'https://images.unsplash.com/photo-1552674605-db6ffd4facb5?w=800',
  'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=400',
  'https://images.unsplash.com/photo-1502904550040-7534597429ae?w=400',
  'https://images.unsplash.com/photo-1513591774-7b60806cc667?w=400',
  'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?w=400',
];
